baseURL = "https://deuteriumlabs.dev/"
languageCode = "en-us"
title = "Deuterium Labs"
theme = "PaperMod"

pagination.pagerSize = 5

[params]
  env = "production" # or "development"
  development_stage = "Beta"
  description = "Two Dudes One Atom - Indie Video Game Development"
  defaultTheme = "dark"
  label.icon = "android-chrome-512x512.png"
  disableThemeToggle = true
  ShowShareButtons = false 
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowToc = false
  tocOpen = false
  customCSS = ["css/extended/custom.css"]
  keywords = [
  "indie games",
  "indie game developer",
  "video games",
  "sci-fi games",
  "sci-fi",
  "pixel art games",
  "open source games",
  "open source development",
  "indie dev",
  "gamedev",
  "game development",
  "unity games",
  "godot games",
  "cyberpunk",
  "space games",
  "retro games",
  "2D games",
  "game studio",
  "game design",
  "indie game studio",
  "open source software",
  "indie games 2025",
  "creative coding",
  "story-driven games",
  "solo dev",
  "experimental games",
  "low poly",
  "art games"
]


[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    identifier = "games"
    name = "Games"
    url = "/games/"
    weight = 2

  [[menu.main]]
    identifier = "blog"
    name = "Dev Blog"
    url = "/posts/"
    weight = 3

[markup]
  [markup.goldmark.renderer]
    unsafe = true


