baseURL = 'https://deuteriumlabs.dev/'
languageCode = 'en-us'
title = 'Deuterium Labs'
theme = 'blowfish'

# Optional: enable dark mode by default
[params]
  defaultTheme = "dark"
# Menus
[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    identifier = "games"
    name = "Games"
    url = "/games/"
    weight = 2

  [[menu.main]]
    identifier = "blog"
    name = "Dev Blog"
    url = "/posts/"
    weight = 3
