baseURL = 'https://deuteriumlabs.dev/'
languageCode = 'en-us'
title = 'Deuterium Labs'
theme = 'terminal'

[params]
  # Some basic Terminal theme settings
  themeColor = "green"  # You can pick: red, blue, green, pink, orange, etc.
  showMenu = true
  fullWidthTheme = false
  centerTheme = true

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    name = "Games"
    url = "/games/"
    weight = 2

  [[menu.main]]
    name = "Dev Blog"
    url = "/posts/"
    weight = 3
