baseurl = "/"
languageCode = "en-us"
theme = "re-terminal"
pagination.pagerSize = 5

[params]
  contentTypeName = "posts"
  themeColor = "blue"
  showMenuItems = 3
  fullWidthTheme = false
  centerTheme = true
  readingTime = true
  [params.banner]
    dismissible = false
    text = "Site under construction!"
    #url = "https://github.com/mirus-ua/hugo-theme-re-terminal"

[languages]
  [languages.en.params]
    title = "Deuterium Labs"
    subtitle = "2 Dudes 1 Atom"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Deuterium Labs"
      logoHomeLink = "/"

[languages.en.menu]
  #[[languages.en.menu.main]]
  #  identifier = "submenu"
  #  name = "Sub menus"
  #  weight = 10
  #[[languages.en.menu.main]]
  #  identifier = "subabout"
  #  name = "About"
  #  url = "/about"
  #  parent = "submenu"
  #[[languages.en.menu.main]]
  #  identifier = "subgames"
  #  name = "Games"
  #  url = "/games"
  #  parent = "submenu"
  [[languages.en.menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
  [[languages.en.menu.main]]
    identifier = "games"
    name = "games"
    url = "/games"
